Updating behaviour of `VaultsSecretsGet` to align with requirements of `secrets cat`
MatrixAI/js-polykey pull request #805
Opened 2024-09-13 09:45 UTC by aryanjassal

### Description

The current `VaultsSecretsGet` only gets a single secret from the vault, and returns it in the form of a `UnaryHandler`, meaning for large files, the RPC call will timeout. It also fetches only one file at a time, so behaviour like UNIX's `cat` command isn't possible.

This PR aims to fix that issue by switching over the RPC handler to a `ServerHandler`, supporting larger files. This PR also adds support for listing the contents of multiple files in order, like what `cat` does.

### Issues Fixed

* Relates to https://github.com/MatrixAI/Polykey-CLI/issues/243
* Closes ENG-356 ([link](https://linear.app/matrix-ai/issue/ENG-356/implement-secrets-cat-command)) 

### Tasks

- [ ] 1. Switch `UnaryHandler` to `StreamHandler`
- [ ] 2. Implement support for concatenating multiple files together
- [ ] 3. Update old test and add new tests
- [ ] 4. Take `stdin` and redirect to `stdout` if no arguments are provided

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

2024-09-13 09:49 UTC, aryanjassal commented
I have implemented basic functionality for displaying file contents for multiple files, and updated the tests in `tests/client/handlers/vaults.test.ts`.

I still need to review the issue spec and all the code to ensure everything's ready for review.

2024-09-13 09:55 UTC, aryanjassal commented
https://github.com/MatrixAI/Polykey-CLI/issues/243#issuecomment-2348535798

I'm going to go ahead with the assumption that we need to implement support for listing contents for files from multiple vaults concurrently, as that makes sense and retains consistency with UNIX commands and `secrets rm`.

2024-09-17 03:11 UTC, aryanjassal commented
The naming of secret commands has changed from what it was. The intention was to keep using the pattern of `SecretsGet`, `SecretsPut`, `SecretsDel`, but to better align with the new commands, these names have been changed to `SecretsGet` (I haven't changed this name yet), `SecretsEdit`, `SecretsRemove`.

We are kinda moving away from the pattern. This was hard to detect as this change was made one-at-a-time across multiple PRs. We might need to look into this and set a standard pattern to follow to ensure consistency.

2024-09-20 03:10 UTC, tegefaulkes requested changes

2024-09-20 03:10 UTC, tegefaulkes commented on src/client/handlers/VaultsSecretsGet.ts
> +            };
Using a generator here isn't necessary since we only get one file and all of it at once. Since we're not implementing streaming here yet you can just use a `withVaultsF` instead.

2024-09-20 03:10 UTC, tegefaulkes commented on src/client/types.ts
> +};
A type of `Array<Array<string>>` is very confusing and doesn't convey the data properly. We want to be consistent with how other commands work. For example the SecretsEnv command functions in a similar way where we get the contents of a bunch of secrets. So we want to mimic how that works.

In that case we just need to use the `SecretIdentifierMessage` as stream them over. So the cat RPC call needs to be a duplex stream. The `VaultsSecretsEnv.ts` already does this. We just need a stripped down version of it for `secrets cat`.

2024-09-20 07:18 UTC, aryanjassal commented on src/client/types.ts
> +};
I've updated both `VaultsSecretsGet` and `VaultsSecretsRemove` to allow streaming of file paths, and also updated the tests accordingly.

2024-09-20 07:20 UTC, aryanjassal commented on src/client/handlers/VaultsSecretsGet.ts
> +            };
I have changed the `withVaultsG` to simply use `withVaults` to get the secret contents. I now yield the fetched contents outside the `withVaults` block.

2024-09-23 05:06 UTC, tegefaulkes reviewed
Small changes, just check your tests are only testing the specific condition we want.

2024-09-23 05:06 UTC, tegefaulkes commented on src/client/handlers/VaultsSecretsRemove.ts
> +    }
You don't need a boolean here, you can use the fact that `metadata` is defined to deal with it.

`if (metadata == null) metadata = secretRemoveMessage.metadata ?? {};`

2024-09-23 05:06 UTC, tegefaulkes commented on tests/client/handlers/vaults.test.ts
> +  });
name of the test doesn't make sense here. We use `vaultsSecretGet` within the new `cat` command. but that handler doesn't do the cat action. So you want to make sure that tests have clear names explaining exactly what you're testing. In this case we're testing if you can get multiple secrets at once, theyre in order and correct.

2024-09-23 23:31 UTC, aryanjassal commented
While I am writing the tests, I can see that we use RPC calls everywhere, even when we don't need to. For example, if we are testing `vaultsSecretsGet` and `vaultsSecretsRemove`, then we will have RPC handlers for `vaultsSecretsNew`, `vaultsSecretsMkdir`, `vaultsSecretsStat`, etc. as other RPC handlers we use to help perform vault operations in the tests.

This introduces slowdowns as each RPC call takes time to complete. A faster method of doing the same would be to acquire a vault, and perform `writeF` on the vault filesystem directly. It should speed up all our tests.

@tegefaulkes and I had a chat about this, and he was also of the same opinion as I, but he mentioned how all the tests would need to be updated to ensure consistency.

How should I deal with this? Do I make a new issue tracking this? It should be relatively straightforward, so maybe this can be something @brynblack could attempt once she gets into Polykey Core development.

2024-09-24 00:05 UTC, tegefaulkes commented
It's some thing we can address later. I think we should make a new issue for it. It should be a general review and refactor of the vaults domain tests. I think one for the CLI and one for Polykey. You mentioned that the vaults tests is one big test file. We should look into splitting that out again but we need to check if it still crashes the CI. The other part is dealing with the `vaultOps.test.ts` testfile. Currently its the longest running tests by far so if we can speed it up or split it into parts that would help as well.

2024-09-24 00:11 UTC, tegefaulkes approved these changes

2024-09-24 00:11 UTC, tegefaulkes commented
Looks good to me.

2024-09-24 04:36 UTC, aryanjassal commented
All tasks have been completed for this PR, all checks are passing, and reviews has also been approved. Merging.

2024-09-24 04:36 UTC, merged